feeder: dataset.dataloader_video1.BaseFeeder
phase: train
dataset: phoenix14t
# dataset: phoenix2014-T

work_dir:  ./work_dir/all/pc2p/
batch_size: 8
random_seed: 0
test_batch_size: 8
num_worker: 20
device: 2,3
log_interval: 10000
eval_interval: 1
save_interval: 5
metric: wer
level: word
loss_weights:
  SeqCTC: 1.0
  ConvCTC: 1.0
  Dist: 25.0
  Translation: 0
load_weights:
#/home/hulala/gsw/SLR2022/MixSignGraph/work_dir/phoenix14T/s2g/h5/_best_model.pt
load_checkpoints:
ignore_weights: []

optimizer_args:
  optimizer: Adam
  learning_rate:
    base_lr:  0.0001
    translation: 0 #0.00001
    vlembedding: 0 #0.001
  step: [10, 20, 35]
  learning_ratio: 1

  scheduler:  ScheaL #consine #
  weight_decay: 0.0001
  start_epoch: 0
  num_epoch: 50
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'h5'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0
  input_size: 224

model: slrt_network3d.SLRModel
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1
